# Generated by Django 4.0.4 on 2022-05-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastra',
            fields=[
                ('cadastra_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=30)),
                ('end', models.CharField(max_length=255)),
                ('prof', models.CharField(max_length=50)),
            ],
        ),
    ]
